/* shadows.frag */
#version 460 core


//CameraData
uniform float maxRayDistance;
uniform vec2 textureScale;
uniform vec3 textureOffset;
uniform bool useMipMapping;

//PlayerData
uniform vec3 playerPosition;

//Headlamp
uniform bool headLampEnabled;
uniform float headLampIntensity;

//Sun
uniform vec3 sunDirection;
uniform vec3 sunColour;

//Debug
uniform int debugMode;

//Other
uniform int numVisplanes;
uniform int numWalls;
uniform int numDisplacements;
uniform int numLights;
uniform ivec2 shadowResolution;
uniform ivec2 renderResolution;
uniform bool allowTransparency;


layout(binding=0) uniform sampler2D positionMap;
layout(binding=1) uniform sampler2D normalMap;
layout(binding=2) uniform sampler2DArray textureArray;
layout(rgba32f, binding=0) uniform image2DArray lightMapArray;

struct Visplane {
	vec4 vertices[4];	//2D points
	uint numVertices;	//Number of 2D points
	float height;		//1D height (Z)
	int textureID;		//Texture ID
	uint textureData;	//Texture formatting data.
	vec4 boundingBox;	//Bounding box in 2D.
};
layout(std430, binding=0) buffer visplaneSSBO {
	Visplane visplanes[];
};

struct Wall {
	vec3 start;			//3D start point
	vec3 end;			//3D end point
	vec2 direction;		//2D Direction
	int textureID;		//Texture ID
	uint textureData;	//Texture formatting data
};
layout(std430, binding=1) buffer wallSSBO {
	Wall walls[];
};

struct Displacement {
	vec4 vertices[3];
	vec2 UV[3];
	vec4 normal_texID;
};
layout(std430, binding=4) buffer displacementSSBO {
	Displacement displacements[];
};

struct Light {
	vec3 position;		//Light Position.
	vec3 colour;		//Light Colour.
	float intensity;	//Light Intensity.
	bool enabled;		//Light Validity.
	float _padding;		//Light Padding.
};
layout(std430, binding=3) buffer lightSSBO {
	Light lights[];
};




vec2 fragPosition;

const float INF = 0xFFFFFF;
const float EPSILON = 1e-4f;
const float EPSILON_ALT = 1e-3f;
const dvec2 INVALIDdv2 = dvec2(INF, INF);
const vec2 INVALIDv2 = vec2(INF, INF);
const vec3 INVALIDv3 = vec3(INF, INF, INF);
const vec4 INVALIDv4 = vec4(INF, INF, INF, INF);


layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;



void unpackTextureFormattingBits(
		uint inputBits, out bvec2 isWorldspace,
		out vec2 invTextureScale, out vec2 textureOffset
	) {
	/*
	- Full 32bits; (uint)
		0000 0000 0000 0000 0000 0000 0000 0000
	isWorldspace.x; (bool) [0 / 1]
		1000 0000 0000 0000 0000 0000 0000 0000
	- isWorldspace.y; (bool) [0 / 1]
		0100 0000 0000 0000 0000 0000 0000 0000
	- textureScale.x; ((8-bit uint) / 16.0f) [0.0 - 16.0]
		0011 1111 1100 0000 0000 0000 0000 0000
	- textureScale.y; ((8-bit uint) / 16.0f) [0.0 - 16.0]
		0000 0000 0011 1111 1100 0000 0000 0000
	- textureOffset.x; ((7-bit uint) / 128.0f) [0.0 - 1.0]
		0000 0000 0000 0000 0011 1111 1000 0000
	- textureOffset.y; ((7-bit uint) / 128.0f) [0.0 - 1.0]
		0000 0000 0000 0000 0000 0000 0111 1111
	*/

	isWorldspace = bvec2(
		bool(inputBits & 0x80000000),
		bool(inputBits & 0x40000000)
	);

	invTextureScale = 16.0f / vec2(
		float((inputBits >> 22) & 0xFF),
		float((inputBits >> 14) & 0xFF)
	);

	textureOffset = vec2(
		float((inputBits >> 7) & 0x7F),
		float((inputBits >> 0) & 0x7F)
	) / 128.0f;
}




//GLSL Cross only works on vec3.
double cross2D(dvec2 a, dvec2 b) {
	return a.x * b.y - a.y * b.x;
}
float cross2D(vec2 a, vec2 b) {
	return a.x * b.y - a.y * b.x;
}




//Walls

float xUVFromWorldspace(vec2 intersectPoint, Wall thisWall) {
	return mix(intersectPoint.x, intersectPoint.y, float(abs(thisWall.direction.y) > abs(thisWall.direction.x)));
}
float xUVFromWallspace(vec2 intersectPoint, Wall thisWall) {
	if (abs(thisWall.direction.y) > abs(thisWall.direction.x)) {
		return (intersectPoint.y - thisWall.start.y) / (thisWall.end.y - thisWall.start.y);
	}
	return (intersectPoint.x - thisWall.start.x) / (thisWall.end.x - thisWall.start.x);
}

vec2 getWallUV(Wall thisWall, vec3 intersectPoint) {
	float wallLowZ = thisWall.start.z, wallTopZ = thisWall.end.z;


	bvec2 useWorldSpace;
	vec2 invTextureScale;
	vec2 textureOffset;
	unpackTextureFormattingBits(
		thisWall.textureData, useWorldSpace,
		invTextureScale, textureOffset
	);



	//xUV calculation.
	float xUV;
	if (useWorldSpace.x) {
		xUV = xUVFromWorldspace(intersectPoint.xy, thisWall);
	} else {
		xUV = xUVFromWallspace(intersectPoint.xy, thisWall);
	}
	xUV *= invTextureScale.x;

	xUV = clamp(fract(xUV + textureOffset.x), 0.0f, 1.0f);


	float a = (intersectPoint.z - thisWall.start.z) / (thisWall.end.z - thisWall.start.z);
	float fragZ = mix(wallLowZ, wallTopZ, a);

	float yUVWorld = 1.0f - fragZ * invTextureScale.y;
	float yUVLocal = 1.0f - (a * invTextureScale.y);

	float yUV = mix(yUVLocal, yUVWorld, float(useWorldSpace.y));

	return vec2(xUV, yUV) + textureOffset;
}




//Visplanes
vec2 getVisplaneUV(vec2 position2D, Visplane plane) {
	bvec2 useWorldSpace;
	vec2 invTextureScale;
	vec2 textureOffset;
	unpackTextureFormattingBits(
		plane.textureData, useWorldSpace,
		invTextureScale, textureOffset
	);

	vec2 UV = position2D.xy * invTextureScale;
	return UV - floor(UV) + textureOffset;
}

vec2 getVertex(Visplane plane, uint index) {
	uint actualIndex = index / 2;
	return (index % 2 == 0) ? plane.vertices[actualIndex].xy : plane.vertices[actualIndex].zw;
}

bool isInsideVP(vec2 point2D, Visplane plane) {
	if (
		((point2D.x < plane.boundingBox.x) || (point2D.x > plane.boundingBox.z)) ||
		((point2D.y < plane.boundingBox.y) || (point2D.y > plane.boundingBox.w))
	) {return false; /* Outside bounding box. */}
	for (uint i=0; i<plane.numVertices; i++) {
		vec2 a = getVertex(plane, i);
		vec2 b = getVertex(plane, (i + 1) % plane.numVertices);
		vec2 edge = b - a;
		vec2 toPoint = point2D - a;
		vec2 normal = vec2(-edge.y, edge.x); //90° Anti-Clockwise

		if (dot(normal, toPoint) < EPSILON) {return false; /* Point is outside the edge */}
	}
	return true;
}






//LOS
bool checkLOS(vec3 pointA, vec3 pointB, int thisIndex=-1, int foundType=0) {
	vec3 LOSDelta = pointB - pointA;

	//Iterate through all the walls. (2D)
	for (int idx=0; idx<numWalls; idx++) {
		Wall thisWall = walls[idx];
		if (idx == thisIndex && foundType == 1) {continue; /* Wall is the index calling the LOS check. */}
		vec2 wallNormal = vec2(-thisWall.direction.y, thisWall.direction.x);
		float projStart = dot(pointA.xy-thisWall.start.xy, wallNormal);
		float projEnd = dot(pointB.xy-thisWall.start.xy, wallNormal);
		if (projStart * projEnd >= 0.0f) {continue; /* Ray never crosses wall. */}

		float t = (projStart) / (projEnd - projStart);
		vec3 intersectPoint = pointA - LOSDelta * t;
		vec3 minWall = min(thisWall.start, thisWall.end);
		vec3 maxWall = max(thisWall.start, thisWall.end);
		if (
		    intersectPoint.x + EPSILON_ALT < minWall.x || intersectPoint.x - EPSILON_ALT > maxWall.x ||
		    intersectPoint.y + EPSILON_ALT < minWall.y || intersectPoint.y - EPSILON_ALT > maxWall.y ||
		    intersectPoint.z + EPSILON_ALT < minWall.z || intersectPoint.z - EPSILON_ALT > maxWall.z
		) {
			//Outside of valid wall segment.
			continue;
		}

		if (allowTransparency) {
			vec2 UV = getWallUV(thisWall, vec3(intersectPoint));
			if (textureLod(textureArray, vec3(UV.xy, thisWall.textureID), 0.0f).a >= 0.5f) {
				return true;
			}
		} else {
			return true;
		}
	}


	//Iterate through all visplanes. (3D-ish)
	for (int idx=0; idx<numVisplanes; idx++) {
		Visplane thisPlane = visplanes[idx];
		if (idx == thisIndex && foundType == 2) {continue; /* Visplane is the index calling the LOS check. */}
		if (thisPlane.height < min(pointA.z, pointB.z) || thisPlane.height > max(pointA.z, pointB.z)) {continue;}


		if (abs(LOSDelta.z) < EPSILON) {continue;}

		float tFrac = (thisPlane.height - pointA.z) / LOSDelta.z;
		if (tFrac <= 0.0 || tFrac >= 1.0) {continue;}

		vec2 intersectPoint = (pointA + LOSDelta * tFrac).xy;
		if (isInsideVP(intersectPoint.xy, thisPlane)) {
			if (allowTransparency) {
				vec2 UV = getVisplaneUV(intersectPoint, thisPlane);
				if (textureLod(textureArray, vec3(UV.xy, thisPlane.textureID), 0.0f).a >= 0.5f) {
					return true;
				}
			} else {
				return true;
			}
		}
	}

	for (int idx=0; idx<numDisplacements; idx++) {
		Displacement thisDisp = displacements[idx];
		if (idx == thisIndex && foundType == 3) {continue; /* Displacement is the index calling the LOS check. */}

		vec3 edgeA = thisDisp.vertices[1].xyz - thisDisp.vertices[0].xyz;
		vec3 edgeB = thisDisp.vertices[2].xyz - thisDisp.vertices[0].xyz;
		vec3 rayCrossEdgeB = cross(LOSDelta, edgeB);
		float det = dot(edgeA, rayCrossEdgeB);

		if (det > -EPSILON && det < EPSILON) {continue; /* Near parallel */}

		float invDeterminant = 1.0f / det;
		vec3 s = pointA - thisDisp.vertices[0].xyz;
		float u = invDeterminant * dot(s, rayCrossEdgeB);
	    if ((u < 0 && abs(u) > EPSILON) || (u > 1 && abs(u-1) > EPSILON)) {
	        continue; //No hit.
	    }

	    vec3 sCrossEdgeA = cross(s, edgeA);
	    float v = invDeterminant * dot(LOSDelta, sCrossEdgeA);
	    if ((v < 0 && abs(v) > EPSILON) || (u + v > 1 && abs(u + v - 1) > EPSILON)) {
	    	continue; //No hit.
	    }

	    float t = invDeterminant * dot(edgeB, sCrossEdgeA);
	    if (t > EPSILON) {
			if (allowTransparency) {
				vec2 UV = ((1.0f - u - v) * thisDisp.UV[0]) + (u * thisDisp.UV[1]) + (v * thisDisp.UV[2]);
				if (textureLod(textureArray, vec3(UV.xy, thisDisp.normal_texID.w), 0.0f).a >= 0.5f) {
					return true;
				}
			} else {
				return true;
			}
	    }
 	}

	return false;
}




float getNormalDot(vec3 normal, vec3 direction) {
	if (dot(normal, normal) < EPSILON) {return 1.0f; /* When normal is invalid (all 0s, used on sprites/sky where no normal exists) then treat it as 1.0f. */}
	return dot(normal, direction);
}


void exit(ivec3 framePosition) {
	imageStore(lightMapArray, framePosition, vec4(0.0f, 0.0f, 0.0f, 1.0f));
}


void main() {
	uint screenX = gl_GlobalInvocationID.x;
	uint screenY = gl_GlobalInvocationID.y;
	uint lightIndex = gl_GlobalInvocationID.z;
	if ((screenX >= renderResolution.x) || (screenY >= renderResolution.y) || (lightIndex >= numLights + 2)) {return; /* Offscreen or out of range. */}

	fragPosition = vec2(screenX, screenY);
	ivec3 framePosition = ivec3(screenX, screenY, lightIndex);
	vec2 thisFramePosition = vec2(fragPosition / vec2(shadowResolution));
	vec4 data = texture(positionMap, thisFramePosition);
	vec3 origin = data.xyz;

	int iData = int(data.w);
	int type = iData & 0x3;
	int index = iData >> 2;

	vec3 normal = texture(normalMap, thisFramePosition).xyz;


	vec3 lightColour = vec3(0.0f, 0.0f, 0.0f);
	if ((lightIndex == numLights + 1)) {
		//Headlamp
		if (!headLampEnabled) {exit(framePosition); return; /* Headlamp is turned off, don't bother calculating. */}

		const vec3 headLampColour = vec3(1.0f, 1.0f, 1.0f);

		vec3 d = origin - playerPosition;
		float distanceSQ = dot(d,d);
		float attenuation = max(0.0, 1.0 - (distanceSQ / (headLampIntensity*headLampIntensity))); //Intensity fades with distance to light.
		float brightness = clamp(attenuation, 0.0f, 1.0f);

		lightColour = headLampColour * brightness;



	} else if (lightIndex == numLights) {
		//Sun & sky's lighting
		if (dot(sunColour, sunColour) < 0.025f) {exit(framePosition); return; /* Sun's effect is near 0 and can be ignored. */}

		if ((debugMode > 0) || (type == 0x0)) {
			imageStore(lightMapArray, framePosition, vec4(1.0f, 1.0f, 1.0f, 1.0f));
			return;
		}

		float sunNormalDot = getNormalDot(normal, normalize(sunDirection));
		vec3 offset = normal * 0.01f;
		bool sunBlocked = checkLOS(origin + offset, origin + offset + sunDirection * maxRayDistance, index, type);
		if ((sunNormalDot >= 0.0f) && !sunBlocked) {
			float sunNormalContrib = (sunNormalDot * 0.5f) + 0.5f;
			lightColour = sunColour.rgb * sunNormalContrib;
		}


	} else {
		//Iterate through all lights.
		Light thisLight = lights[lightIndex];
		if (!thisLight.enabled) {exit(framePosition); return; /* Light is turned off. */}

		vec3 delta = thisLight.position - origin;
		if (dot(delta,delta) < EPSILON_ALT) {
			lightColour = thisLight.colour;
		} else {
			vec3 lightDir = normalize(delta);
			float normalDot = getNormalDot(normal, lightDir);
			if (normalDot <= EPSILON_ALT) {exit(framePosition); return; /* Surface would reflect no lighting due to cosine of angles being negative. */}

			float distSQ = dot(delta, delta);
			float attenuation = max(0.0, 1.0 - abs(distSQ / (thisLight.intensity*thisLight.intensity))); //Intensity fades with distance to light.
			if (attenuation <= EPSILON_ALT) {exit(framePosition); return; /* Light is too dim to contribute. */}

			
			//Shadow Checks
			bool inShadow = checkLOS(thisLight.position, origin, index, type);

			if (!inShadow) {
				lightColour = thisLight.colour * attenuation;
			}
		}
	}


	imageStore(lightMapArray, framePosition, vec4(lightColour.rgb, 1.0f));
}
