/* shadows.frag */
#version 460 core
#extension GL_ARB_bindless_texture : require

layout(binding=0) uniform sampler2D positionMap;
layout(binding=1) uniform sampler2D normalMap;
layout(rgba32f, binding=0) writeonly uniform image2DArray lightMapArray;

struct Visplane {
	vec4 vertices[4];	//2D points
	uint numVertices;	//Number of 2D points
	float height;		//1D height (Z)
	uint textureData1;	//1st Texture formatting data.
	uint textureData2;	//2nd Texture formatting data.
	vec4 boundingBox;	//Bounding box in 2D.
	uint64_t shadowMapHandle; //64 bit handle.
};
layout(std430, binding=0) buffer visplaneSSBO {
	Visplane visplanes[];
};

struct Wall {
	vec3 start;			//3D start point
	vec3 end;			//3D end point
	vec2 direction;		//2D Direction
	uint textureData1;	//1st Texture formatting data.
	uint textureData2;	//2nd Texture formatting data.
	uint64_t shadowMapHandle; //64 bit handle.
};
layout(std430, binding=1) buffer wallSSBO {
	Wall walls[];
};

struct Displacement {
	vec4 vertices[3];
	vec2 UV[3];
	vec4 normal_texID;
};
layout(std430, binding=4) buffer displacementSSBO {
	Displacement displacements[];
};

struct Light {
	vec3 position;		//Light Position.
	vec3 colour;		//Light Colour.
	float intensity;	//Light Intensity.
	bool enabled;		//Light Validity.
	float _padding;		//Light Padding.
};
layout(std430, binding=3) buffer lightSSBO {
	Light lights[];
};



uniform int surfaceIndex;
uniform int surfaceType;
uniform vec2 textureResolution;



vec2 fragPosition;

#define INF 0xFFFFFF
#define PI 3.141592f
#define EPSILON 1e-4f
#define EPSILON_ALT 1e-3f
#define INVALIDdv2 dvec2(INF, INF)
#define INVALIDv2 vec2(INF, INF)
#define INVALIDv3 vec3(INF, INF, INF)
#define INVALIDv4 vec4(INF, INF, INF, INF)



layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;



void exit(ivec3 framePosition) {
	imageStore(lightMapArray, framePosition, vec4(0.0f, 0.0f, 0.0f, 1.0f));
}




void main() {
	uint pixelX = gl_GlobalInvocationID.x;
	uint pixelY = gl_GlobalInvocationID.y;
	if ((pixelX >= renderResolution.x) || (pixelY >= renderResolution.y)) {return; /* Offscreen. */}
	vec2 UV = vec2(pixelX, pixelY) / textureResolution;

	vec3 position;
	vec3 normal;
	switch(type) {
		case 0x1: {
			//Wall
			Wall thisWall = walls[surfaceIndex];
			position = vec3(
				mix(thisWall.start.xy, thisWall.end.xy, UV.x),
				mix(thisWall.start.z, thisWall.end.z, UV.y)
			);
			normal = vec3(-thisWall.direction.y, thisWall.direction.x, 0.0f);
		}
		case 0x2: {
			//Visplane
			Visplane thisPlane = visplanes[surfaceIndex];
			position = vec3(
				mix(thisPlane.boundingBox.xy, thisPlane.boundingBox.zw, UV),
				thisPlane.height
			);
			normal = vec3(0.0f, 0.0f, 1.0f);
		}
	}

	imageStore(lightMapArray, framePosition, vec4(lightColour.rgb, 1.0f));
}
