/* lightingStaticPrecompute.comp */
//At runtime, once
#version 460 core
#extension GL_ARB_gpu_shader_int64 : enable

layout(rgba32f, binding=0) writeonly uniform image2D frontShadowmap;
layout(rgba32f, binding=1) writeonly uniform image2D backShadowmap;
layout(binding=2) uniform sampler2DArray textureArray;


//Shadow specific
uniform ivec2 shadowMapResolution;
uniform vec3 objectStart;
uniform vec3 objectEnd;
uniform vec3 surfaceNormal;
uniform bool allowTransparency;

//Other
uniform int numVisplanes;
uniform int numWalls;
uniform int numDisplacements;
uniform int numLights;



#define INF 0xFFFFFF
#define PI 3.141592f
#define EPSILON 1e-4f
#define EPSILON_ALT 1e-3f
#define INVALIDv2 vec2(INF, INF)
#define INVALIDv3 vec3(INF, INF, INF)
#define INVALIDv4 vec4(INF, INF, INF, INF)


struct Visplane {
	vec4 vertices[4];	//2D points
	uint numVertices;	//Number of 2D points
	float height;		//1D height (Z)
	uint textureData1;	//1st Texture formatting data.
	uint textureData2;	//2nd Texture formatting data.
	vec4 boundingBox;	//Bounding box in 2D.
	uint64_t lightingHandles[2]; //ARB shadowMap handles.
};
layout(std430, binding=0) buffer visplaneSSBO {
	Visplane visplanes[];
};

struct Wall {
	vec3 start;			//3D start point
	vec3 end;			//3D end point
	vec2 direction;		//2D Direction
	uint textureData1;	//1st Texture formatting data.
	uint textureData2;	//2nd Texture formatting data.
	uint64_t lightingHandles[2]; //ARB shadowMap handles.
};
layout(std430, binding=1) buffer wallSSBO {
	Wall walls[];
};

struct Displacement {
	vec4 vertices[3];
	vec2 UV[3];
	vec4 normal_texID;
};
layout(std430, binding=4) buffer displacementSSBO {
	Displacement displacements[];
};

struct Light {
	vec3 position;		//Light Position.
	vec3 colour;		//Light Colour.
	float intensity;	//Light Intensity.
	bool enabled;		//Light Validity.
	float _padding;		//Light Padding.
};
layout(std430, binding=3) buffer lightSSBO {
	Light lights[];
};




void unpackTextureFormattingBits1(
		uint inputBits, out bvec4 textureFlags,
		out int textureID
	) {
	/*
	- Full 32bits; (uint)
		0000 0000 0000 0000 0000 0000 0000 0000
	- textureFlags; (4 bit flags) [0 - 15]
		1111 0000 0000 0000 0000 0000 0000 0000
	- textureID; (12 bit uint) [0 - 65535]
		0000 1111 1111 1111 0000 0000 0000 0000
	*/
	textureFlags = bvec4(
		bool(inputBits & 0x80000000),
		bool(inputBits & 0x40000000),
		bool(inputBits & 0x20000000),
		bool(inputBits & 0x10000000)
	);

	uint texIDbits = (inputBits >> 16) & 0xFFF;
	textureID = (texIDbits == 0xFFF) ? -1 : int(texIDbits);
}
void unpackTextureFormattingBits2(
		uint inputBits, out bvec2 isWorldspace,
		out vec2 invTextureScale, out vec2 textureOffset
	) {
	/*
	- Full 32bits; (uint)
		0000 0000 0000 0000 0000 0000 0000 0000
	isWorldspace.x; (bool) [0 / 1]
		1000 0000 0000 0000 0000 0000 0000 0000
	- isWorldspace.y; (bool) [0 / 1]
		0100 0000 0000 0000 0000 0000 0000 0000
	- textureScale.x; ((8-bit uint) / 16.0f) [0.0 - 16.0]
		0011 1111 1100 0000 0000 0000 0000 0000
	- textureScale.y; ((8-bit uint) / 16.0f) [0.0 - 16.0]
		0000 0000 0011 1111 1100 0000 0000 0000
	- textureOffset.x; ((7-bit uint) / 128.0f) [0.0 - 1.0]
		0000 0000 0000 0000 0011 1111 1000 0000
	- textureOffset.y; ((7-bit uint) / 128.0f) [0.0 - 1.0]
		0000 0000 0000 0000 0000 0000 0111 1111
	*/

	isWorldspace = bvec2(
		bool(inputBits & 0x80000000),
		bool(inputBits & 0x40000000)
	);

	invTextureScale = 16.0f / vec2(
		float((inputBits >> 22) & 0xFF),
		float((inputBits >> 14) & 0xFF)
	);

	textureOffset = vec2(
		float((inputBits >> 7) & 0x7F),
		float((inputBits >> 0) & 0x7F)
	) / 128.0f;
}




//GLSL Cross only works on vec3.
float cross2D(vec2 a, vec2 b) {
	return a.x * b.y - a.y * b.x;
}




//Walls

float xUVFromWorldspace(vec2 intersectPoint, Wall thisWall) {
	return mix(intersectPoint.x, intersectPoint.y, float(abs(thisWall.direction.y) > abs(thisWall.direction.x)));
}
float xUVFromWallspace(vec2 intersectPoint, Wall thisWall) {
	if (abs(thisWall.direction.y) > abs(thisWall.direction.x)) {
		return (intersectPoint.y - thisWall.start.y) / (thisWall.end.y - thisWall.start.y);
	}
	return (intersectPoint.x - thisWall.start.x) / (thisWall.end.x - thisWall.start.x);
}

vec2 getWallUV(Wall thisWall, vec3 intersectPoint, out int textureID) {
	float wallLowZ = thisWall.start.z, wallTopZ = thisWall.end.z;

	//1st formatting data;
	bvec4 textureFlags;
	unpackTextureFormattingBits1(
		thisWall.textureData1, textureFlags,
		textureID
	);

	//2nd formatting data;
	bvec2 useWorldSpace;
	vec2 invTextureScale;
	vec2 textureOffset;
	unpackTextureFormattingBits2(
		thisWall.textureData2, useWorldSpace,
		invTextureScale, textureOffset
	);



	//xUV calculation.
	float xUV;
	if (useWorldSpace.x) {
		xUV = xUVFromWorldspace(intersectPoint.xy, thisWall);
	} else {
		xUV = xUVFromWallspace(intersectPoint.xy, thisWall);
	}
	xUV *= invTextureScale.x;

	xUV = clamp(fract(xUV + textureOffset.x), 0.0f, 1.0f);


	float a = (intersectPoint.z - thisWall.start.z) / (thisWall.end.z - thisWall.start.z);
	float fragZ = mix(wallLowZ, wallTopZ, a);

	float yUVWorld = 1.0f - fragZ * invTextureScale.y;
	float yUVLocal = 1.0f - (a * invTextureScale.y);

	float yUV = mix(yUVLocal, yUVWorld, float(useWorldSpace.y));

	return vec2(xUV, yUV) + textureOffset;
}




//Visplanes
vec2 getVisplaneUV(vec2 position2D, Visplane plane, out int textureID) {
	//1st formatting data;
	bvec4 textureFlags;
	unpackTextureFormattingBits1(
		plane.textureData1, textureFlags,
		textureID
	);

	//2nd formatting data;
	bvec2 useWorldSpace;
	vec2 invTextureScale;
	vec2 textureOffset;
	unpackTextureFormattingBits2(
		plane.textureData2, useWorldSpace,
		invTextureScale, textureOffset
	);

	vec2 UV = position2D.xy * invTextureScale;
	return UV - floor(UV) + textureOffset;
}

vec2 getVertex(Visplane plane, uint index) {
	uint actualIndex = index / 2;
	return (index % 2 == 0) ? plane.vertices[actualIndex].xy : plane.vertices[actualIndex].zw;
}

bool isInsideVP(vec2 point2D, Visplane plane) {
	if (
		((point2D.x < plane.boundingBox.x) || (point2D.x > plane.boundingBox.z)) ||
		((point2D.y < plane.boundingBox.y) || (point2D.y > plane.boundingBox.w))
	) {return false; /* Outside bounding box. */}
	for (uint i=0; i<plane.numVertices; i++) {
		vec2 a = getVertex(plane, i);
		vec2 b = getVertex(plane, (i + 1) % plane.numVertices);
		vec2 edge = b - a;
		vec2 toPoint = point2D - a;
		vec2 normal = vec2(-edge.y, edge.x); //90° Anti-Clockwise

		if (dot(normal, toPoint) < EPSILON) {return false; /* Point is outside the edge */}
	}
	return true;
}






//LOS
bool checkLOS(vec3 pointA, vec3 pointB, int thisIndex=-1, int foundType=0) {
	vec3 LOSDelta = pointB - pointA;

	//Iterate through all the walls. (2D)
	for (int idx=0; idx<numWalls; idx++) {
		Wall thisWall = walls[idx];
		if (idx == thisIndex && foundType == 1) {continue; /* Wall is the index calling the LOS check. */}
		vec2 wallNormal = vec2(-thisWall.direction.y, thisWall.direction.x);
		float projStart = dot(pointA.xy-thisWall.start.xy, wallNormal);
		float projEnd = dot(pointB.xy-thisWall.start.xy, wallNormal);
		if (projStart * projEnd >= 0.0f) {continue; /* Ray never crosses wall. */}

		float t = projStart / (projEnd - projStart);
		vec3 intersectPoint = pointA - LOSDelta * t;
		vec3 minWall = min(thisWall.start, thisWall.end);
		vec3 maxWall = max(thisWall.start, thisWall.end);
		if (
			intersectPoint.x + EPSILON_ALT < minWall.x || intersectPoint.x - EPSILON_ALT > maxWall.x ||
			intersectPoint.y + EPSILON_ALT < minWall.y || intersectPoint.y - EPSILON_ALT > maxWall.y ||
			intersectPoint.z + EPSILON_ALT < minWall.z || intersectPoint.z - EPSILON_ALT > maxWall.z
		) {
			//Outside of valid wall segment.
			continue;
		}

		if (allowTransparency) {
			int textureID;
			vec2 UV = getWallUV(thisWall, vec3(intersectPoint), textureID);
			if (textureLod(textureArray, vec3(UV.xy, textureID), 0.0f).a >= 0.5f) {
				return true;
			}
		} else {
			return true;
		}
	}


	//Iterate through all visplanes. (3D-ish)
	for (int idx=0; idx<numVisplanes; idx++) {
		Visplane thisPlane = visplanes[idx];
		if (idx == thisIndex && foundType == 2) {continue; /* Visplane is the index calling the LOS check. */}
		if (thisPlane.height < min(pointA.z, pointB.z) || thisPlane.height > max(pointA.z, pointB.z)) {continue;}


		if (abs(LOSDelta.z) < EPSILON) {continue;}

		float tFrac = (thisPlane.height - pointA.z) / LOSDelta.z;
		if (tFrac <= 0.0 || tFrac >= 1.0) {continue;}

		vec2 intersectPoint = (pointA + LOSDelta * tFrac).xy;
		if (isInsideVP(intersectPoint.xy, thisPlane)) {
			if (allowTransparency) {
				int textureID;
				vec2 UV = getVisplaneUV(intersectPoint, thisPlane, textureID);
				if (textureLod(textureArray, vec3(UV.xy, textureID), 0.0f).a >= 0.5f) {
					return true;
				}
			} else {
				return true;
			}
		}
	}

	for (int idx=0; idx<numDisplacements; idx++) {
		Displacement thisDisp = displacements[idx];
		if (idx == thisIndex && foundType == 3) {continue; /* Displacement is the index calling the LOS check. */}

		vec3 edgeA = thisDisp.vertices[1].xyz - thisDisp.vertices[0].xyz;
		vec3 edgeB = thisDisp.vertices[2].xyz - thisDisp.vertices[0].xyz;
		vec3 rayCrossEdgeB = cross(LOSDelta, edgeB);
		float det = dot(edgeA, rayCrossEdgeB);

		if (det > -EPSILON && det < EPSILON) {continue; /* Near parallel */}

		float invDeterminant = 1.0f / det;
		vec3 s = pointA - thisDisp.vertices[0].xyz;
		float u = invDeterminant * dot(s, rayCrossEdgeB);
		if ((u < 0 && abs(u) > EPSILON) || (u > 1 && abs(u-1) > EPSILON)) {
			continue; //No hit.
		}

		vec3 sCrossEdgeA = cross(s, edgeA);
		float v = invDeterminant * dot(LOSDelta, sCrossEdgeA);
		if ((v < 0 && abs(v) > EPSILON) || (u + v > 1 && abs(u + v - 1) > EPSILON)) {
			continue; //No hit.
		}

		float t = invDeterminant * dot(edgeB, sCrossEdgeA);
		if (t > EPSILON) {
			if (allowTransparency) {
				vec2 UV = ((1.0f - u - v) * thisDisp.UV[0]) + (u * thisDisp.UV[1]) + (v * thisDisp.UV[2]);
				if (textureLod(textureArray, vec3(UV.xy, thisDisp.normal_texID.w), 0.0f).a >= 0.5f) {
					return true;
				}
			} else {
				return true;
			}
		}
	}

	return false;
}




float getNormalDot(vec3 normal, vec3 direction, out bool shouldUseSpecularHighlights) {
	if (dot(normal, normal) < EPSILON) {
		shouldUseSpecularHighlights = false;
		return 1.0f; /* When normal is invalid (all 0s, used on sprites/sky where no normal exists) then treat it as 1.0f. */
	}
	shouldUseSpecularHighlights = true;
	return dot(normal, direction);
}


void exit(ivec2 fragPosition, const bool useFrontFace) {
	if (useFrontFace) {
		imageStore(frontShadowmap, fragPosition, vec4(0.0f, 0.0f, 0.0f, 1.0f));
	} else {
		imageStore(backShadowmap, fragPosition, vec4(0.0f, 0.0f, 0.0f, 1.0f));
	}
}



layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;


void main() {
	ivec2 fragPosition = ivec2(gl_GlobalInvocationID.xy);
	vec2 fragDecimal = vec2(fragPosition) / vec2(shadowMapResolution);
	if (max(fragDecimal.x, fragDecimal.y) > 1.0f) {return; /* Outside of the range of the texture. */}
	vec3 position3D = vec3(
		mix(objectStart.xy, objectEnd.xy, fragDecimal.x),
		mix(objectStart.z, objectEnd.z, fragDecimal.y)
	);


	bool useFrontFace = gl_GlobalInvocationID.z == 1;
	vec3 thisNormal = (useFrontFace) ? surfaceNormal : -surfaceNormal;
	position3D += thisNormal * 0.01f; //Slight offset to avoid the surface occluding itself.


	vec3 lightColour = vec3(0.0f, 0.0f, 0.0f);
	for (uint index=0; index<numLights; index++) {
		Light thisLight = lights[index];
		if (!thisLight.enabled) {continue;}

		vec3 lightDelta = thisLight.position - position3D;

		float normalDot = dot(surfaceNormal, normalize(lightDelta));
		if (normalDot <= EPSILON_ALT) {continue; /* Surface would reflect no lighting due to cosine of angles being negative. */}

		float distSQ = dot(lightDelta, lightDelta);
		float attenuation = max(0.0, 1.0 - abs(distSQ / (thisLight.intensity*thisLight.intensity))); //Intensity fades with distance to light.
		if (attenuation <= EPSILON_ALT) {continue; /* Light is too dim to contribute. */}

		//Shadow Checks
		bool inShadow = checkLOS(thisLight.position, position3D);

		if (!inShadow) {
			lightColour += thisLight.colour * attenuation;
		}
	}



	if (useFrontFace) {
		imageStore(frontShadowmap, fragPosition, vec4(position3D.rgb, 1.0f));
	} else {
		imageStore(backShadowmap, fragPosition, vec4(position3D.rgb, 1.0f));
	}
}