/* lightingPrecomutePerFrame.comp */
#version 460 core
#extension GL_ARB_bindless_texture : require

layout(binding=0) uniform sampler2D positionMap;
layout(binding=1) uniform sampler2D normalMap;
layout(rgba32f, binding=0) writeonly uniform image2DArray lightMapArray;

struct Visplane {
	vec4 vertices[4];	//2D points
	uint numVertices;	//Number of 2D points
	float height;		//1D height (Z)
	uint textureData1;	//1st Texture formatting data.
	uint textureData2;	//2nd Texture formatting data.
	vec4 boundingBox;	//Bounding box in 2D.
	uint64_t shadowMapHandle; //64 bit handle.
};
layout(std430, binding=0) buffer visplaneSSBO {
	Visplane visplanes[];
};

struct Wall {
	vec3 start;			//3D start point
	vec3 end;			//3D end point
	vec2 direction;		//2D Direction
	uint textureData1;	//1st Texture formatting data.
	uint textureData2;	//2nd Texture formatting data.
	uint64_t shadowMapHandle; //64 bit handle.
};
layout(std430, binding=1) buffer wallSSBO {
	Wall walls[];
};




vec2 fragPosition;

#define INF 0xFFFFFF
#define PI 3.141592f
#define EPSILON 1e-4f
#define EPSILON_ALT 1e-3f
#define INVALIDdv2 dvec2(INF, INF)
#define INVALIDv2 vec2(INF, INF)
#define INVALIDv3 vec3(INF, INF, INF)
#define INVALIDv4 vec4(INF, INF, INF, INF)



layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;



void exit(ivec3 framePosition) {
	imageStore(lightMapArray, framePosition, vec4(0.0f, 0.0f, 0.0f, 1.0f));
}




void main() {
	uint screenX = gl_GlobalInvocationID.x;
	uint screenY = gl_GlobalInvocationID.y;
	if ((screenX >= renderResolution.x) || (screenY >= renderResolution.y)) {return; /* Offscreen. */}

	fragPosition = vec2(screenX, screenY);
	ivec3 framePosition = ivec3(screenX, screenY, 1);
	vec2 thisFramePosition = vec2(fragPosition / vec2(shadowResolution));
	vec4 data = texture(positionMap, thisFramePosition);
	vec3 origin = data.xyz;

	int iData = int(data.w);
	int type = iData & 0x7;
	int index = iData >> 3;

	vec2 UV;
	uint64_t shadowMapHandle;
	if (type == 0x1) { //Wall
		Wall thisWall = walls[index];

		vec3 startDelta = origin - thisWall.start;
		float startDeltaSQ = dot(startDelta2D.xy, startDelta2D.xy);
		vec3 wallDelta = thisWall.end - thisWall.start;
		float wallDeltaSQ = dot(wallDelta2D.xy, wallDelta2D.xy);

		UV = vec2(
			startDeltaSQ / wallDeltaSQ,
			startDelta.z / wallDelta.z
		);
		shadowMapHandle = thisWall.shadowMapHandle;

	} else if (type == 0x2) { //Visplane
		Visplane thisPlane = visplanes[index];

		vec2 startDelta = origin.xy - thisPlane.boundingBox.xy;
		vec2 planeDelta = thisPlane.boundingBox.zw - thisPlane.boundingBox.xy;

		UV = vec2(
			startDelta / planeDelta
		);
		shadowMapHandle = thisPlane.shadowMapHandle;

	}
	sampler2D shadowSampler = sampler2D(shadowMapHandle);
	vec3 lightColour = texture(shadowSampler, UV).rgb;

	imageStore(shadowSampler, framePosition, vec4(lightColour.rgb, 1.0f));
}
