/* shadow.comp */
#version 460 core

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;


//CameraData
uniform float maxRayDistance;
uniform float maxRayAngle;
uniform float verticalFOV;
uniform float zoomFactor;
uniform vec2 textureScale;
uniform vec3 textureOffset;
uniform bool useMipMapping;

//PlayerData
uniform float playerViewAngle;
uniform float playerViewRoll;
uniform float playerViewPitch;
uniform vec3 playerPosition;
uniform bool zoom;
uniform ivec2 renderResolution;

//Debug
uniform int debugMode;

//Headlamp
uniform bool headLampEnabled;
uniform int headLampFlicker;

//Sun
uniform vec3 sunDirection;
uniform vec3 sunColour;

//Other
uniform int numVisplanes;
uniform int numWalls;
uniform int numDisplacements;
uniform int numLights;



struct Visplane {
	vec2 start;			//Visplane Start.
	vec2 end;			//Visplane End.
	float height;		//Visplane Height.
	int textureID;		//Visplane Texture.
	vec2 _padding;		//Visplane Padding
};
layout(std430, binding=0) buffer visplaneSSBO {
	Visplane visplanes[];
};

struct Wall {
	vec3 start;		//Wall Start.
	vec3 end;		//Wall End.
	vec2 direction;	//Wall 2D Direction
	int textureID;	//Wall Texture.
	float _padding;	//Wall Validity.
};
layout(std430, binding=1) buffer wallSSBO {
	Wall walls[];
};

struct Displacement {
	vec4 vertices[3];
	vec2 UV[3];
	vec4 normal_texID;
};
layout(std430, binding=5) buffer displacementSSBO {
	Displacement displacements[];
};

struct Light {
	vec3 position;		//Light Position.
	vec3 colour;		//Light Colour.
	float intensity;	//Light Intensity.
	bool enabled;		//Light Validity.
	float _padding;		//Light Padding.
};
layout(std430, binding=3) buffer lightSSBO {
	Light lights[];
};
struct Ray {
	dvec3 position, end;
	dvec3 direction;
};



layout(rg32f, binding=0) uniform image2DArray shadowMap;

uniform ivec2 shadowMapResolution;

vec2 pxPosition;
float fragDepth;
const float INF = 0xFFFFFF;
const float EPSILON = 1e-4f;


//GLSL Cross only works on vec3.
double cross2D(dvec2 a, dvec2 b) {
	return a.x * b.y - a.y * b.x;
}
float cross2D(vec2 a, vec2 b) {
	return a.x * b.y - a.y * b.x;
}

float rayIntersectDistance(Ray ray, Wall wall, out double t) {
	dvec2 origin = ray.position.xy;
	dvec2 rayDelta = ray.end.xy - ray.position.xy;

	dvec2 wallOrigin = wall.start.xy;
	dvec2 wallDir = wall.end.xy - wallOrigin;

	double rayDeltaCrosswallDirInv = 1.0f / cross2D(rayDelta, wallDir);
	if (abs(rayDeltaCrosswallDirInv) < EPSILON) {return INF; /* Ray and wall are parallel */}

	dvec2 orDir = wallOrigin - origin;
	t = cross2D(orDir, wallDir) * rayDeltaCrosswallDirInv;
	double u = cross2D(orDir, rayDelta) * rayDeltaCrosswallDirInv;

	if (t < 0.0 || u < 0.0 || u > 1.0) return INF;

	return float(t * maxRayDistance);
}


int closestIndex = -1;

float getDepth(vec3 position, vec3 direction) {
	float minDistanceSQ = maxRayDistance*maxRayDistance;
	Ray fragRay;
	fragRay.position = position;
	fragRay.direction = direction;
	fragRay.end = position + direction * maxRayDistance;
	dvec3 rayDelta = fragRay.end - position;



	//Iterate through all the walls. (2D)
	for (int idx=0; idx<numWalls; idx++) {
		Wall thisWall = walls[idx];

		double t;
		float dist = rayIntersectDistance(fragRay, thisWall, t);

		double rayZ = position.z + (t * direction.z * maxRayDistance);
		if ((rayZ < thisWall.start.z) || (rayZ > thisWall.end.z)) {continue; /* Above/Below wall */}

		float distSQ = dist*dist;
		if (distSQ < minDistanceSQ) {
			minDistanceSQ = distSQ;
			closestIndex = idx;
		}
	}


	//Iterate through all visplanes. (3D)
	for (int idx=0; idx<numVisplanes; idx++) {
		Visplane thisPlane = visplanes[idx];
		if (thisPlane.height < min(position.z, fragRay.end.z) || thisPlane.height > max(position.z, fragRay.end.z)) {continue;}


		if (abs(rayDelta.z) < EPSILON) {continue;}

		double tFrac = (thisPlane.height - position.z) / rayDelta.z;
		if (tFrac <= 0.0 || tFrac >= 1.0) {continue;}

		dvec3 intersectPoint = position + rayDelta * tFrac;
		if (
			intersectPoint.x >= min(thisPlane.start.x, thisPlane.end.x) - EPSILON &&
			intersectPoint.x <= max(thisPlane.start.x, thisPlane.end.x) + EPSILON &&
			intersectPoint.y >= min(thisPlane.start.y, thisPlane.end.y) - EPSILON &&
			intersectPoint.y <= max(thisPlane.start.y, thisPlane.end.y) + EPSILON
		) {
			dvec3 delta = intersectPoint - position;
			float distSQ = float(dot(delta, delta));
			if (distSQ < minDistanceSQ) {
				minDistanceSQ = distSQ;
				closestIndex = -idx;
			}
		}
	}

	/*
	for (int idx=0; idx<numDisplacements; idx++) {
		continue;
		Displacement thisDisp = displacements[idx];

		vec3 edgeA = thisDisp.vertices[1].xyz - thisDisp.vertices[0].xyz;
		vec3 edgeB = thisDisp.vertices[2].xyz - thisDisp.vertices[0].xyz;
		vec3 rayCrossEdgeB = cross(rayDelta, edgeB);
		float det = dot(edgeA, rayCrossEdgeB);

		if (det > -EPSILON && det < EPSILON) {continue; /* Near parallel /}

		float invDeterminant = 1.0f / det;
		vec3 s = pointA - thisDisp.vertices[0].xyz;
		float u = invDeterminant * dot(s, rayCrossEdgeB);
	    if ((u < 0 && abs(u) > EPSILON) || (u > 1 && abs(u-1) > EPSILON)) {
	        continue; //No hit.
	    }

	    vec3 sCrossEdgeA = cross(s, edgeA);
	    float v = invDeterminant * dot(rayDelta, sCrossEdgeA);
	    if ((v < 0 && abs(v) > EPSILON) || (u + v > 1 && abs(u + v - 1) > EPSILON)) {
	    	continue; //No hit.
	    }

	    float t = invDeterminant * dot(edgeB, sCrossEdgeA);
	    if (t > EPSILON) {
	    	return true;
	    }
 	}
 	*/

	return pow(minDistanceSQ, 0.25); //Double sqrt.
}


void main() {
	pxPosition = gl_GlobalInvocationID.xy;
	ivec2 framePosition = ivec2(pxPosition);
	int lightIndex = int(gl_GlobalInvocationID.z);
	Light thisLight = lights[lightIndex];
	fragDepth = maxRayDistance;

	vec2 ratio = vec2(360.0f, 180.0f) / vec2(shadowMapResolution);

	float yawAngle = radians(pxPosition.x) * ratio.x;
	float pitchAngle = radians(pxPosition.y - 180.0f) * ratio.y;
	vec3 direction = normalize(vec3(
		sin(yawAngle) * cos(pitchAngle),
		cos(yawAngle) * cos(pitchAngle),
		sin(pitchAngle)
	));


	fragDepth = getDepth(thisLight.position, direction);

	imageStore(shadowMap, ivec3(framePosition, lightIndex), vec4(fragDepth, closestIndex, 0.0f, 1.0f));
}