/* lightingStaticFrame.fixed.frag */
//Per frame, samples maps. Does not use ARB textures.
#version 460 core


layout(binding=0) uniform sampler2D positionMap;
layout(binding=1) uniform sampler2D normalMap;
layout(binding=2) uniform sampler2DArray shadowMaps;
layout(rgba32f, binding=0) writeonly uniform image2DArray lightMapArray;


uniform ivec2 renderResolution;
uniform vec3 playerPosition;


struct Visplane {
	vec4 vertices[4];	//2D points
	uint numVertices;	//Number of 2D points
	float height;		//1D height (Z)
	uint textureData1;	//1st Texture formatting data.
	uint textureData2;	//2nd Texture formatting data.
	vec4 boundingBox;	//Bounding box in 2D.
	uint type;			//Visplanetype.
	float extra;		//Extra data.
	uint lightingHandles[4]; //ARB shadowMap handles.
};
layout(std430, binding=0) buffer visplaneSSBO {
	Visplane visplanes[];
};

struct Wall {
	vec3 start;			//3D start point
	vec3 end;			//3D end point
	vec2 direction;		//2D Direction
	uint textureData1;	//1st Texture formatting data.
	uint textureData2;	//2nd Texture formatting data.
	uint type;			//Walltype.
	float extra;		//Extra data.
	uint lightingHandles[8]; //ARB shadowMap handles.
};
layout(std430, binding=1) buffer wallSSBO {
	Wall walls[];
};



layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;


#define T_NONE 0x0u
#define T_WALL 0x1u
#define T_VISPLANE 0x2u
#define T_DISPLACEMENT 0x3u
#define T_SPRITE 0x4u

void main() {
	uint screenX = gl_GlobalInvocationID.x;
	uint screenY = gl_GlobalInvocationID.y;
	uint lightIndex = gl_GlobalInvocationID.z;
	if ((screenX >= renderResolution.x) || (screenY >= renderResolution.y) || (lightIndex > 0)) {return; /* Offscreen or out of range. */}
	ivec2 framePosition = ivec2(screenX, screenY);


	vec4 data = texture(positionMap, vec2(framePosition) / vec2(renderResolution));
	vec3 position3D = data.xyz;
	int iData = int(data.w);
	uint type = uint(iData & 0x7);
	int index = iData >> 3;
	vec3 fragNormal = texture(normalMap, vec2(framePosition) / vec2(renderResolution)).xyz;

	vec4 lightColour;
	vec2 uv;
	int idx;
	switch (type) {
		case T_NONE: { //Sky
			lightColour = vec4(1.0f, 1.0f, 1.0f, 1.0f);
			break;
		}
		case T_WALL: { //Walls
			Wall thisWall = walls[index];
			vec3 range = thisWall.end - thisWall.start;
			vec3 local = position3D - thisWall.start;
			float UVx;
			if (abs(range.x) > abs(range.y)) {
				UVx = (position3D.x - thisWall.start.x) / range.x;
			} else {
				UVx = (position3D.y - thisWall.start.y) / range.y;
			}
			uv = vec2(
				UVx,
				fract(local.z/range.z)
			);

			vec3 fragDir = playerPosition - position3D;
			vec2 wallNormal = vec2(-thisWall.direction.y, thisWall.direction.x);
			idx = int(dot(wallNormal.xy, (playerPosition-position3D).xy) > 0.0f);
			lightColour = texture(shadowMaps, vec3(uv.xy, thisWall.lightingHandles[idx])).rgba;
			break;
		}
		case T_VISPLANE: { //Visplanes
			Visplane thisVisplane = visplanes[index];
			vec2 range = thisVisplane.boundingBox.zw - thisVisplane.boundingBox.xy;
			uv = (position3D.xy - thisVisplane.boundingBox.xy) / range;
			idx = int(playerPosition.z > thisVisplane.height);
			lightColour = texture(shadowMaps, vec3(uv.xy, thisVisplane.lightingHandles[idx])).rgba;
			break;
		}
		case T_DISPLACEMENT: { //Displacements
			lightColour = vec4(1.0f, 1.0f, 1.0f, 1.0f);
			break;
		}
		case T_SPRITE: { //Sprites
			lightColour = vec4(1.0f, 1.0f, 1.0f, 1.0f);
			break;
		}
	}

	//imageStore(lightMapArray, ivec3(framePosition.xy, 0), vec4(idx, 0.0f, 0.0f, 0.0f));
	//imageStore(lightMapArray, ivec3(framePosition.xy, 0), vec4((fragNormal/2)+.5, 0.0f));
	imageStore(lightMapArray, ivec3(framePosition.xy, 0), lightColour);
}