/* lightingStaticFrame.arb.frag */
//Per frame, samples maps. uses ARB texturing.
#version 460 core
#extension GL_ARB_bindless_texture : require
#extension GL_ARB_gpu_shader_int64 : enable


layout(binding=0) uniform sampler2D positionMap;
layout(binding=1) uniform sampler2D normalMap;
layout(rgba32f, binding=0) writeonly uniform image2DArray lightMapArray;


//General
uniform ivec2 renderResolution;
uniform vec3 playerPosition;
uniform float maxRayDistance;

//Headlamp
uniform bool headLampEnabled;
uniform float headLampIntensity;



struct Visplane {
	vec4 vertices[4];	//2D points
	uint numVertices;	//Number of 2D points
	float height;		//1D height (Z)
	uint textureData1;	//1st Texture formatting data.
	uint textureData2;	//2nd Texture formatting data.
	vec4 boundingBox;	//Bounding box in 2D.
	uint type;			//Visplanetype.
	float extra;		//Extra data.
	uint lightingHandles[4]; //ARB shadowMap handles.
};
layout(std430, binding=0) buffer visplaneSSBO {
	Visplane visplanes[];
};

struct Wall {
	vec3 start;			//3D start point
	vec3 end;			//3D end point
	vec2 direction;		//2D Direction
	uint textureData1;	//1st Texture formatting data.
	uint textureData2;	//2nd Texture formatting data.
	uint type;			//Walltype.
	float extra;		//Extra data.
	uint lightingHandles[8]; //ARB shadowMap handles.
};
layout(std430, binding=1) buffer wallSSBO {
	Wall walls[];
};


uint64_t getHandle(uint handles[4], const bool useFront) {
	if (useFront) {
		return (uint64_t(handles[0]) << 32u) | uint64_t(handles[1]);
	} else {
		return (uint64_t(handles[2]) << 32u) | uint64_t(handles[3]);
	}
}


#define EPSILON 1e-5f
#define T_NONE 0x0u
#define T_WALL 0x1u
#define T_VISPLANE 0x2u
#define T_DISPLACEMENT 0x3u
#define T_SPRITE 0x4u


layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;


sampler2D getMapFromHandles(uint high, uint low) {
	uint64_t fullHandle = (uint64_t(high) << 32) | uint64_t(low);
	return sampler2D(fullHandle);
}

float getNormalDot(vec3 normal, vec3 direction) {
	if (dot(normal, normal) < EPSILON) {
		return 1.0f; /* When normal is invalid (all 0s, used on sprites/sky where no normal exists) then treat it as 1.0f. */
	}
	return dot(normal, direction);
}


void main() {
	uint screenX = gl_GlobalInvocationID.x;
	uint screenY = gl_GlobalInvocationID.y;
	uint lightIndex = gl_GlobalInvocationID.z;
	if ((screenX >= renderResolution.x) || (screenY >= renderResolution.y) || (lightIndex > 1u)) {return; /* Offscreen or out of range. */}
	ivec2 framePosition = ivec2(screenX, screenY);
	vec2 screenUV = vec2(framePosition) / vec2(renderResolution);


	vec4 data = texture(positionMap, screenUV);
	vec3 position3D = data.xyz;
	int iData = int(data.w);
	uint type = uint(iData & 0x7);
	int index = iData >> 3;
	vec3 fragNormal = texture(normalMap, screenUV).xyz;

	vec4 lightColour;
	if (lightIndex > 0u) { //Headlamp.
		if (!headLampEnabled) {
			lightColour = vec4(0.0f, 0.0f, 0.0f, 1.0f);
		} else {
			const vec3 headLampColour = vec3(1.0f, 1.0f, 1.0f);

			vec3 delta3D = playerPosition - position3D;
			float distanceSQ = dot(delta3D, delta3D);
			float normalDot = clamp(getNormalDot(fragNormal, normalize(delta3D)), 0.0f, 1.0f);
			float attenuation = max(0.0f, 1.0f - (distanceSQ / (headLampIntensity*headLampIntensity))) * normalDot; //Intensity fades with distance to light.
			float brightness = clamp(attenuation, 0.0f, 1.0f);

			lightColour = vec4(headLampColour * brightness, 1.0f);
		}


	} else {
		lightColour = vec4(1.0f, 1.0f, 1.0f, 1.0f);
		vec2 uv;
		int idx;
		switch (type) {
			case T_NONE: { //Sky
				lightColour = vec4(1.0f, 1.0f, 1.0f, 1.0f);
				break;
			}
			case T_WALL: { //Walls
				Wall thisWall = walls[index];
				vec3 range = thisWall.end - thisWall.start;
				vec3 local = position3D - thisWall.start;
				float UVx;
				if (abs(range.x) > abs(range.y)) {
					UVx = (position3D.x - thisWall.start.x) / range.x;
				} else {
					UVx = (position3D.y - thisWall.start.y) / range.y;
				}
				uv = vec2(
					UVx,
					fract(local.z/range.z)
				);

				vec3 fragDir = playerPosition - position3D;
				vec2 wallNormal = vec2(-thisWall.direction.y, thisWall.direction.x);
				idx = int(dot(wallNormal.xy, (playerPosition-position3D).xy) > 0.0f);

				sampler2D thisMap = getMapFromHandles(thisWall.lightingHandles[(idx*2)], thisWall.lightingHandles[(idx*2)+1]);
				lightColour = texture(thisMap, uv.xy).rgba;
				break;
			}
			case T_VISPLANE: { //Visplanes
				Visplane thisVisplane = visplanes[index];
				vec2 range = thisVisplane.boundingBox.zw - thisVisplane.boundingBox.xy;
				uv = (position3D.xy - thisVisplane.boundingBox.xy) / range;
				idx = int(playerPosition.z > thisVisplane.height);

				sampler2D thisMap = getMapFromHandles(thisVisplane.lightingHandles[(idx*2)], thisVisplane.lightingHandles[(idx*2)+1]);
				lightColour = texture(thisMap, uv.xy).rgba;
				break;
			}
			case T_DISPLACEMENT: { //Displacements
				lightColour = vec4(1.0f, 1.0f, 1.0f, 1.0f);
				break;
			}
			case T_SPRITE: { //Sprites
				lightColour = vec4(1.0f, 1.0f, 1.0f, 1.0f);
				break;
			}
		}
	}

	imageStore(lightMapArray, ivec3(framePosition.xy, lightIndex), lightColour);
}