/* lightingStaticFrame.fixed.frag */
//Per frame, samples maps. Does not use ARB textures.
#version 460 core


layout(binding=0) uniform sampler2D positionMap;
layout(binding=1) uniform sampler2DArray shadowMaps;
layout(rgba32f, binding=0) writeonly uniform image2DArray lightMapArray;


uniform ivec2 renderResolution;



struct Visplane {
	vec4 vertices[4];	//2D points
	uint numVertices;	//Number of 2D points
	float height;		//1D height (Z)
	uint textureData1;	//1st Texture formatting data.
	uint textureData2;	//2nd Texture formatting data.
	vec4 boundingBox;	//Bounding box in 2D.
	uint type;			//Visplanetype.
	float extra;		//Extra data.
	uint lightingHandles[4]; //ARB shadowMap handles.
};
layout(std430, binding=0) buffer visplaneSSBO {
	Visplane visplanes[];
};

struct Wall {
	vec3 start;			//3D start point
	vec3 end;			//3D end point
	vec2 direction;		//2D Direction
	uint textureData1;	//1st Texture formatting data.
	uint textureData2;	//2nd Texture formatting data.
	uint type;			//Walltype.
	float extra;		//Extra data.
	uint lightingHandles[8]; //ARB shadowMap handles.
};
layout(std430, binding=1) buffer wallSSBO {
	Wall walls[];
};



layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;


void main() {
	uint screenX = gl_GlobalInvocationID.x;
	uint screenY = gl_GlobalInvocationID.y;
	uint lightIndex = gl_GlobalInvocationID.z;
	if ((screenX >= renderResolution.x) || (screenY >= renderResolution.y) || (lightIndex >= 3)) {return; /* Offscreen or out of range. */}
	ivec2 framePosition = ivec2(screenX, screenY);


	vec4 data = texture(positionMap, vec2(framePosition) / vec2(renderResolution));
	vec3 position3D = data.xyz;
	int iData = int(data.w);
	int type = iData & 0x7;
	int index = iData >> 3;

	vec4 lightColour;
	vec2 uv;
	switch (type) {
		case 0x0: { //Sky
			lightColour = vec4(1.0f, 1.0f, 1.0f, 1.0f);
			break;
		}
		case 0x1: { //Walls
			Wall thisWall = walls[index];
			vec3 range = thisWall.end - thisWall.start;
			vec3 local = position3D - thisWall.start;
			uv = vec2(
				dot(local.xy, local.xy) / dot(range.xy, range.xy),
				local.z / range.z
			);
			lightColour = texture(shadowMaps, vec3(uv.xy, thisWall.lightingHandles[0])).rgba;
			break;
		}
		case 0x2: { //Visplanes
			Visplane thisVisplane = visplanes[index];
			vec2 range = thisVisplane.boundingBox.zw - thisVisplane.boundingBox.xy;
			uv = (position3D.xy - thisVisplane.boundingBox.xy) / range;
			lightColour = texture(shadowMaps, vec3(uv.xy, thisVisplane.lightingHandles[0])).rgba;
			break;
		}
		case 0x3: { //Displacements
			lightColour = vec4(1.0f, 1.0f, 1.0f, 1.0f);
			break;
		}
		case 0x4: { //Sprites
			lightColour = vec4(1.0f, 1.0f, 1.0f, 1.0f);
			break;
		}
	}

	imageStore(lightMapArray, ivec3(framePosition.xy, 0), vec4(lightColour.rgb, 1.0f));
}